=== nicolashaddad80/revision/tests/crowdlending.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT crowdlending (projet+)>

        <!ELEMENT projet (montant,offre*)>
        <!ATTLIST projet nom ID #REQUIRED >

        <!ELEMENT montant (#PCDATA) >
        <!ELEMENT offre EMPTY>
        <!ATTLIST offre
                montant CDATA #REQUIRED
                taux CDATA #REQUIRED
                numéro CDATA #REQUIRED
                état (EN-COURS |NON-RETENUE| RETENUE)   #REQUIRED>

=== nicolashaddad80/revision/tests/ExempleSujetPlateforme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE crowdlending SYSTEM "crowdlending.dtd">
<crowdlending>
  <projet nom="ABC">
    <montant>30000</montant>
  </projet>
  <projet nom="XYZ">
    <montant>120000</montant>
    <offre montant="50" taux="7.5" numéro="1" état="EN-COURS" />
    <offre montant="90" taux="8.3" numéro="2" état="EN-COURS" />
    <offre montant="20" taux="9.9" numéro="3" état="EN-COURS" />
    <offre montant="50" taux="5.0" numéro="4" état="EN-COURS" />
    <offre montant="68" taux="6.9" numéro="5" état="EN-COURS" />
  </projet>
</crowdlending>
